version: "3"

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
Â© 2022 GitHub, Inc.
Terms
Privacy
Security